workflows:
  ios-capacitor-testflight:
    name: 🍏 GOODBUILD iOS TestFlight (Upload-only)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: 16.4
      node: 20.19.6
      groups:
        - ios_config
        - app_store_credentials
      vars:
        # 📌 SINGLE SOURCE OF TRUTH
        APP_VERSION: "1.0.1" 
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.apex.tradeline"

    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods

    scripts:
      - name: 🔎 Runtime versions (fail fast)
        script: |
          node --version
          npm --version

      - name: 📦 Install dependencies
        script: |
          npm ci --no-audit --prefer-offline

      - name: ✅ GOODBUILD quality + verify gates
        script: |
          npm run lint
          npm run typecheck
          npm run test:unit
          npm run test:e2e:smoke
          npm run verify:app
          npm run verify:icons
          npm run verify:console

      - name: 🧱 Build web assets + sync Capacitor (iOS only)
        script: |
          npm run build
          npx cap sync

      - name: 🧩 Assert iOS AppIcon exists (hard fail if missing)
        script: |
          # Inject Version directly into archive command
          cd ios/App
          xcrun agvtool new-marketing-version "$APP_VERSION"
          xcrun agvtool new-version -all "$BUILD_NUMBER"
          cd ../..

      - name: 🔐 Use provisioning profiles (GOODBUILD)
        script: |
          xcode-project use-profiles \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: 📦 Build IPA (GOODBUILD)
        script: |
          cd android
          # Use standard AGP properties to override version without file editing
          ./gradlew bundleRelease \
            -Pandroid.injected.version.code=$BUILD_NUMBER \
            -Pandroid.injected.version.name=$APP_VERSION \
            -Pandroid.injected.signing.store.file=$(echo $CM_KEYSTORE_PATH) \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - build/ios/export/*.ipa
      - android/app/build/outputs/bundle/release/*.aab
