workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight (No-Mac)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      groups:
        - "Apple Store Keys"   # must match your Codemagic group name exactly
      xcode: latest
      cocoapods: default
      node: 20.11.1
      npm: 10

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Preflight – verify required envs exist (safe)
        script: |
          set -euo pipefail
          required=(APP_STORE_CONNECT_API_KEY APP_STORE_CONNECT_KEY_ID APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_TEAM_ID)
          for k in "${required[@]}"; do
            if [ -z "${!k:-}" ]; then
              echo "::error::Missing required env var: $k (check Group: Apple Store Keys)"
              exit 1
            fi
          done
          # basic sanity on private key length (masked in logs)
          [ "${#APP_STORE_CONNECT_API_KEY}" -ge 100 ] || { echo "::error::APP_STORE_CONNECT_API_KEY seems too short (paste full .p8)"; exit 1; }
          echo "✓ Env looks good."

      - name: Install deps & build web
        script: |
          npm ci
          npm run build

      - name: Sync Capacitor + CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod install --repo-update

      - name: Xcode archive (automatic signing)
        script: |
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            -quiet \
            clean archive

      - name: Export IPA
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>destination</key><string>export</string>
            <key>teamID</key><string>${APP_STORE_CONNECT_TEAM_ID}</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID         # Key ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID   # Issuer ID (UUID)
          private_key: $APP_STORE_CONNECT_API_KEY   # FULL .p8 contents
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
        # cancel_previous_submissions: true
