workflows:

  ios-capacitor-testflight:

    name: TradeLine 24/7 iOS TestFlight

    max_build_duration: 60

    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_config
        - appstore_credentials
      vars:

        XCODE_WORKSPACE: ios/App/App.xcworkspace

        XCODE_SCHEME: App

        BUNDLE_ID: com.apex.tradeline

        APP_VERSION: "1.1.0"

        PROJECT_BUILD_NUMBER: $CM_BUILD_NUMBER

      xcode: 16.4

      node: 20.19.6
      npm: 10

      cocoapods: default

      ios_signing:

        distribution_type: app_store

        bundle_identifier: com.apex.tradeline

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods
    
    scripts:

      - name: Install Node dependencies

        script: |

          set -eo pipefail

          node -v
          npm -v
          npm ci

      - name: Quality gates

        script: |

          set -eo pipefail

          npm run lint && npm run typecheck && npm run test:unit

      - name: Verify visual assets

        script: |

          set -eo pipefail

          STRICT_ICONS=true npm run verify:icons

          node scripts/validate-hero-source.mjs

      - name: Playwright smoke
        script: |

          set -eo pipefail

          npx playwright install --with-deps chromium
          npm run test:e2e:smoke

      - name: Build web assets

        script: |

          set -eo pipefail

          npm run build

      - name: Prepare iOS native project
        script: |
          set -eo pipefail
          # Restore missing 1024×1024 App Store icon (if present in brand assets)
          mkdir -p ios/App/App/Assets.xcassets/AppIcon.appiconset
          cp -f public/assets/brand/App_Icons/ios/AppStore1024.png \
            ios/App/App/Assets.xcassets/AppIcon.appiconset/icon-1024.png || true
          # Ensure Podfile sets minimum iOS deployment target to 15.0
          if grep -qE "platform :ios" ios/App/Podfile; then
            sed -i.bak -E "s/platform :ios, '[0-9.]+'/platform :ios, '15.0'/" ios/App/Podfile
          else
            printf "platform :ios, '15.0'\n%s" "$(cat ios/App/Podfile)" > ios/App/Podfile.tmp && mv ios/App/Podfile.tmp ios/App/Podfile
          fi
          # Force iOS deployment target to 15.0 in the Xcode project
          perl -pi -e "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" \
            ios/App/App.xcodeproj/project.pbxproj

      - name: Sync Capacitor

        script: |
          set -eo pipefail
          npx cap sync ios

      - name: Install CocoaPods
        script: |

          set -eo pipefail

          cd ios/App && pod install --repo-update

      - name: Set iOS version numbers
        script: |

          set -eo pipefail

          export PROJECT_BUILD_NUMBER="${CM_BUILD_NUMBER:-1}"
          bash scripts/set-ios-version-from-codemagic.sh

      - name: Configure code signing

        script: |
          set -eo pipefail

          xcode-project use-profiles --custom-export-options '{"testFlightInternalTestingOnly": true}'

      - name: Build archive and IPA

        script: |

          set -eo pipefail

          # Detect Xcode workspace or project
          WORKSPACE="$(find ios -maxdepth 4 -name '*.xcworkspace' | head -n 1 || true)"
          PROJECT="$(find ios -maxdepth 4 -name '*.xcodeproj' | head -n 1 || true)"

          if [[ -n "$WORKSPACE" ]]; then
            echo "Using workspace: $WORKSPACE"
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "${XCODE_SCHEME:-App}" \
              --config Release \
              --archive-flags="-destination 'generic/platform=iOS'"
          elif [[ -n "$PROJECT" ]]; then
            echo "Using project: $PROJECT"
            xcode-project build-ipa \
              --project "$PROJECT" \
              --scheme "${XCODE_SCHEME:-App}" \
              --config Release \
              --archive-flags="-destination 'generic/platform=iOS'"
          else
            echo "ERROR: No Xcode workspace or project found under ios/"
            echo "Directory listing:"
            ls -R ios || true
            exit 2
          fi



    artifacts:

      - build/ios/ipa/*.ipa

      - /tmp/xcodebuild_logs/*.log

      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

      - playwright-report/**/*
      - dist/**/*


    publishing:
      app_store_connect:

        api_key: $APP_STORE_CONNECT_PRIVATE_KEY

        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER

        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        submit_to_testflight: true

        beta_groups:

          - Internal Testers


    triggering:
      events:
        - push
      branch_patterns:

        - pattern: main

          include: true

          source: true

  # ────────────────────────────────────────────────────────────────────────────
  # ANDROID BUILD
  # ────────────────────────────────────────────────────────────────────────────
  android-capacitor-release:
    name: Android • Capacitor bundleRelease
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      groups:
        - android_signing
      vars:
        APP_VERSION: "1.1.0"
      node: 20.19.6
      npm: 10
      java: 17
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle
    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm -v
          npm ci
      - name: Quality gates
        script: npm run lint && npm run typecheck && npm run test:unit
      - name: Verify visual assets
        script: |
          set -eo pipefail
          STRICT_ICONS=true npm run verify:icons
          node scripts/validate-hero-source.mjs
      - name: Playwright smoke
        script: |
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke
      - name: Set Android version numbers
        script: |
          set -eo pipefail
          bash scripts/set-android-version.sh
      - name: Build Android App Bundle
        script: bash scripts/build-android.sh
      - name: Verify artifacts
        script: bash scripts/verify-codemagic.sh
    artifacts:
      - android/app/build/outputs/**/*.aab
      - playwright-report/**/*
      - dist/**/*
      - build-artifacts-sha256.txt

  # ────────────────────────────────────────────────────────────────────────────
  # WEB TESTS
  # ────────────────────────────────────────────────────────────────────────────
  web-tests-only:
    name: Web Tests & Smoke
    instance_type: linux
    max_build_duration: 45
    environment:
      node: 20.19.6
      npm: 10
    cache:
      cache_paths:
        - ~/.npm
    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm -v
          npm ci
      - name: Lint, typecheck, unit tests
        script: npm run lint && npm run typecheck && npm run test:unit
      - name: Build web bundle
        script: npm run build:web
      - name: Install Playwright browsers
        script: npm run test:install-browsers
      - name: Run full Playwright test suite
        script: npx playwright test --reporter=html
    artifacts:
      - playwright-report/**/*
      - dist/**/*
