workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight
    # Use M2 so the warning disappears
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      # Name shown in your Codemagic "Apple Developer Portal" integration
      app_store_connect: APEX Business Systems

    environment:
      groups:
        - appstore_credentials   # TEAM_ID, BUNDLE_ID, DIST_PROFILE_NAME, PROJECT_BUILD_NUMBER (optional)
      xcode: 15.4
      vars:
        IOS_BUILD_NUM: $PROJECT_BUILD_NUMBER

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install deps & build web
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Ensure iOS platform (idempotent)
        script: |
          set -euo pipefail
          XCPROJ="ios/App/App.xcodeproj"
          if [ -d "$XCPROJ" ]; then
            echo "✅ Found iOS project — skipping add"
          else
            echo "🆕 Adding iOS platform…"
            npm i -D @capacitor/ios
            npx cap add ios
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          command -v pod >/dev/null 2>&1 || sudo gem install cocoapods --no-document
          pod repo update || true
          pod install --repo-update
          test -d App.xcworkspace || { echo "❌ CocoaPods didn't produce App.xcworkspace"; exit 1; }

      - name: Set iOS build number from Codemagic (optional)
        script: |
          set -euo pipefail
          if [ -n "${IOS_BUILD_NUM:-}" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${IOS_BUILD_NUM}" ios/App/App/Info.plist || true
            echo "ℹ️  CFBundleVersion set to ${IOS_BUILD_NUM}"
          else
            echo "↪️  IOS_BUILD_NUM not set; skipping Info.plist patch"
          fi

      - name: Install signing certs & provisioning profiles
        script: |
          set -euo pipefail
          # Installs all uploaded .p12 + .mobileprovision from Codemagic UI into a temporary keychain
          keychain initialize
          keychain add-certificates

      - name: Apply provisioning profiles to Xcode project (per-target)
        script: |
          set -euo pipefail
          # Force the correct (manual) profiles into the App and Pods targets
          xcode-project use-profiles --project "ios/App/App.xcodeproj"
          echo "✅ Profiles applied to Xcode project"
          # (If you ever see “applied to Pods target” warnings, this is expected per Codemagic docs.) 

      - name: Xcode archive (manual signing)
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CURRENT_PROJECT_VERSION="${IOS_BUILD_NUM:-1}" \
            -quiet \
            clean archive

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          : "${DIST_PROFILE_NAME:?Set DIST_PROFILE_NAME to your App Store profile name}"
          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>teamID</key><string>${TEAM_ID}</string>
              <key>stripSwiftSymbols</key><true/>
              <key>compileBitcode</key><false/>
              <key>provisioningProfiles</key>
              <dict>
                <key>${BUNDLE_ID}</key><string>${DIST_PROFILE_NAME}</string>
              </dict>
            </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
