workflows:
  ios_capacitor_testflight:
    name: iOS • Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - appstore_credentials   # APP_STORE_CONNECT_* + CERTIFICATE_PRIVATE_KEY
        - ios_config             # TEAM_ID, BUNDLE_ID, etc.
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD: "1"           # must be non-empty; we’ll overwrite in script if you want
      xcode: latest
      node: 20.11.1
      npm: 10
      cocoapods: default

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Resolve version/build
        script: |
          # optionally auto-bump build number at runtime
          if [ -z "$APP_BUILD" ] || ! [[ "$APP_BUILD" =~ ^[0-9]+$ ]]; then
            APP_BUILD="$(date +%y%m%d%H)"
          fi
          echo "Using APP_VERSION=$APP_VERSION / APP_BUILD=$APP_BUILD"

      - name: Install deps & build web
        script: |
          npm ci
          npm run build

      - name: Sync Capacitor + CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod install --repo-update

      - name: Set iOS Info.plist versions
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${APP_VERSION}" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${APP_BUILD}" ios/App/App/Info.plist

      # Automatic iOS code signing: needs RSA-2048 PEM in CERTIFICATE_PRIVATE_KEY
      - name: Fetch signing files (Automatic)
        script: |
          app-store-connect fetch-signing-files \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "$CERTIFICATE_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --create \
            "$BUNDLE_ID"

      - name: Apply profiles to the Xcode project
        script: |
          xcode-project use-profiles

      - name: Xcode archive (Release)
        script: |
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -allowProvisioningUpdates \
            clean archive

      - name: Export IPA for App Store
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/TradeLine247.xcarchive

    publishing:
      app_store_connect:
        # Correct schema (direct fields):
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
