workflows:
  ios_capacitor_testflight:
    name: "iOS • Capacitor → TestFlight"
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups: [appstore_credentials]     # holds APP_STORE_CONNECT_* and (optionally) APPLE_TEAM_ID
      vars:
        APP_VERSION: "1.0.0"             # keep non-empty
      xcode: "16.0"
      cocoapods: "default"
      node: "20.11.1"
      npm: "10"

    scripts:
      - name: "Resolve version/build"
        script: |
          set -euo pipefail
          : "${APP_VERSION:=1.0.0}"
          APP_BUILD="$(date +%y%m%d%H%M)"
          echo "APP_VERSION=$APP_VERSION" >> "$CM_ENV"
          echo "APP_BUILD=$APP_BUILD"     >> "$CM_ENV"

      - name: "Build web"
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: "Capacitor copy + CocoaPods"
        script: |
          set -euo pipefail
          npx cap copy ios              # use 'sync' only when you need native dep updates
          cd ios/App
          pod install                   # deterministic; add --repo-update only if needed

      - name: "Set Info.plist version"
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $APP_BUILD"             ios/App/App/Info.plist

      - name: "Archive"
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" -configuration Release -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates clean archive

      - name: "Export IPA"
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
          </dict></plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - "$CM_BUILD_DIR/export/*.ipa"
      - "$CM_BUILD_DIR/App.xcarchive"

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
