- name: Ensure iOS platform & CocoaPods
  script: |
    set -euo pipefail

    # 0) Debug: show current tree (helps if this ever fails)
    echo "== before =="
    ls -la || true
    test -d ios && ls -la ios || true
    test -d ios/App && ls -la ios/App || true

    # 1) Create iOS platform if missing (fresh CI runner)
    if [ ! -d ios/App/App.xcodeproj ]; then
      echo "iOS platform or Xcode project missing → running 'npx cap add ios'"
      rm -rf ios || true
      npx cap add ios
    fi

    # 2) Sync Capacitor (copies web assets + updates plugins)
    npx cap sync ios

    # 3) Install pods inside native iOS app
    cd ios/App
    pod repo update || true
    pod install --repo-update

    echo "== after =="
    ls -la .
    test -d App.xcworkspace && echo "✅ Found App.xcworkspace"
