workflows:
  ios_capacitor_testflight:
    name: iOS • Capacitor → TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      groups:
        - appstore_credentials       # (Codemagic UI group with your Apple/ASC secrets)
      xcode: 15.4                  # Pin Xcode version for consistency
      vars:
        BUNDLE_ID: "com.example.app"   # Your iOS bundle identifier
        TEAM_ID: "ABCDEFGHIJ"          # Your Apple Team ID

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install deps & build web
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Ensure iOS platform (idempotent + self-heal)
        script: |
          set -euo pipefail
          PROJECT_DIR="ios/App"
          XCPROJ="$PROJECT_DIR/App.xcodeproj"
          XCWORK="$PROJECT_DIR/App.xcworkspace"
          if [ -d "$XCPROJ" ] || [ -d "$XCWORK" ]; then
            echo "✅ iOS project exists — skipping add"
          else
            if [ -d ios ]; then
              echo "⚠️ ios/ exists but no Xcode project — re-adding cleanly"
              rm -rf ios
            fi
            echo "🆕 Adding iOS platform..."
            npm i -D @capacitor/ios
            npx cap add ios
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          command -v pod >/dev/null 2>&1 || sudo gem install cocoapods --no-document
          pod repo update || true
          pod install --repo-update
          test -d App.xcworkspace || { echo "❌ CocoaPods didn't produce App.xcworkspace"; exit 1; }

      - name: Preflight ASC vars (fail fast if missing)
        script: |
          set -euo pipefail
          : "${APP_STORE_CONNECT_API_KEY:?Missing APP_STORE_CONNECT_API_KEY (.p8 contents)}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?Missing APP_STORE_CONNECT_KEY_IDENTIFIER (Key ID)}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?Missing APP_STORE_CONNECT_ISSUER_ID (Issuer ID)}"
          echo "✓ ASC vars present"

      - name: Xcode archive (automatic signing)
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            -quiet \
            clean archive

      - name: Export IPA
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>destination</key><string>export</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        api_key:  $APP_STORE_CONNECT_API_KEY       # (full .p8 contents; provided via env group)
        key_id:   $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id:$APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
