workflows:
  ios_systems_audit:
    name: iOS Systems & Functions Audit (no publish)
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
      cocoapods: default
      groups:
        - "Apple Store Keys"   # APP_STORE_CONNECT_* + TEAM_ID
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install deps
        script: |
          set -euo pipefail
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Ensure dist/ for Capacitor
        script: |
          set -euo pipefail
          if [ -f dist/index.html ]; then
            echo "dist/ present ✅"
          elif [ -f build/index.html ]; then
            echo "build/ present; copying to dist/"
            rm -rf dist && mkdir -p dist && cp -a build/. dist/
          else
            echo "❌ No web assets found (dist/ or build/ missing)."
            exit 1
          fi

      - name: Capacitor sync + CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          pod repo update || true
          pod install --repo-update

      - name: Simulator sanity build (no signing)
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath build | xcpretty || true

    artifacts:
      - build/Logs/**/*
    # No publishing in audit workflow.

  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight (No-Mac)
    max_build_duration: 120
    environment:
      xcode: latest
      node: 20
      cocoapods: default
      groups:
        - "Apple Store Keys"
      vars:
        MARKETING_VERSION: "1.0.0"   # bump as needed
        BUILD_NUMBER: "1005"         # > last uploaded build
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install deps
        script: |
          set -euo pipefail
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Ensure dist/ for Capacitor
        script: |
          set -euo pipefail
          if [ -f dist/index.html ]; then
            echo "dist/ present ✅"
          elif [ -f build/index.html ]; then
            echo "build/ present; copying to dist/"
            rm -rf dist && mkdir -p dist && cp -a build/. dist/
          else
            echo "❌ No web assets found (dist/ or build/ missing)."
            exit 1
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          pod repo update || true
          pod install --repo-update

      - name: Build IPA (App Store)
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-method app-store \
            --build-number "$BUILD_NUMBER" \
            --marketing-version "$MARKETING_VERSION"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/**/*
    publishing:
      app_store_connect:
        api_key:  $APP_STORE_CONNECT_API_KEY     # .p8 contents
        key_id:   $APP_STORE_CONNECT_KEY_ID      # Key ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID  # Issuer GUID
        submit_to_testflight: true
        # optional: bundle_id: com.apex.tradeline
