workflows:
  tradeline247-capacitor-testflight:
    name: TradeLine247 → TestFlight (Capacitor)
    instance_type: mac_mini_m2

    # If you have an ASC integration configured, set the name here; else you can remove 'integrations'
    integrations:
      app_store_connect: TradeLine247-ASC-Key

    environment:
      xcode: 16.4
      node: 20
      cocoapods: default
      # Load BOTH of your groups so TEAM_ID is visible:
      groups:
        - appstore_credentials   # APP_STORE_CONNECT_* live here
        - ios_config             # TEAM_ID, XCODE_*, BUNDLE_ID live here
      vars:
        TEAM_ID: "NWGUYF42KW"
        BUNDLE_ID: "com.apex.tradeline"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/ios/App/Pods
        - $CM_BUILD_DIR/node_modules

    scripts:
      - name: Verify env (now non-fatal and clear)
        script: |
          set -e
          for V in TEAM_ID BUNDLE_ID XCODE_SCHEME XCODE_WORKSPACE; do
            if [ -z "${!V:-}" ]; then echo "Missing required env: $V"; exit 1; fi
          done
          echo "TEAM_ID=$TEAM_ID"
          echo "BUNDLE_ID=$BUNDLE_ID"
          echo "XCODE_SCHEME=$XCODE_SCHEME"
          echo "XCODE_WORKSPACE=$XCODE_WORKSPACE"

      - name: Install Node deps & build web assets
        script: |
          set -e
          npm ci || npm install
          if npm run | grep -qE '(^|\s)build(\s|:)'; then
            npm run build
          else
            npx ionic build || true
          fi

      - name: Sync Capacitor iOS wrapper
        script: |
          set -e
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod repo update
          pod install
          cd -

      - name: Fetch signing (ASC integration or env fallback)
        script: |
          set -e
          KEY_ID="${APP_STORE_CONNECT_KEY_IDENTIFIER:-$APP_STORE_CONNECT_KEY_IDENTIFIE}"
          if [ -n "${CM_INTEGRATION_APP_STORE_CONNECT:-}" ]; then
            echo "Using App Store Connect integration"
            app-store-connect fetch-signing-files "$BUNDLE_ID" --create --type IOS_APP_STORE --team-id "$TEAM_ID"
          else
            echo "Using env-based ASC credentials"
            app-store-connect fetch-signing-files "$BUNDLE_ID" --create --type IOS_APP_STORE \
              --key-id "$KEY_ID" \
              --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
              --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
              --team-id "$TEAM_ID"
          fi
          keychain initialize
          keychain add-certificates

      - name: Apply provisioning (scope to your workspace)
        script: |
          set -e
          xcode-project use-profiles --workspace "$XCODE_WORKSPACE"

      - name: Bump build number from TestFlight (optional)
        script: |
          set -e
          APPLE_ID="${APP_APPLE_ID:-$APP_STORE_ID}"
          if [[ "$APPLE_ID" =~ ^[0-9]+$ ]]; then
            LATEST=$(app-store-connect get-latest-testflight-build-number "$APPLE_ID" || echo 0)
            NEXT=$((LATEST + 1))
            echo "Using next build number: $NEXT"
            agvtool new-version -all "$NEXT" || true
          else
            echo "Skipping bump: provide numeric APP_APPLE_ID in env to auto-increment build numbers."
          fi

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-configuration Release \
            --xcargs "DEVELOPMENT_TEAM=$TEAM_ID CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/export_options.plist
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        # If using integration, you can set: auth: integration
        # Using env-based auth to match your current setup (works even with the typo'd KEY var).
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: ${APP_STORE_CONNECT_KEY_IDENTIFIER:-$APP_STORE_CONNECT_KEY_IDENTIFIE}
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal
