You are Google Jules acting as a senior Codemagic + iOS release engineer.

GOAL:
Fix the Codemagic build failing at preflight due to missing APP_STORE_CONNECT_KEY_ID and ensure TestFlight publishing works consistently using environment-variable auth.

EVIDENCE:
Build log shows env var exists as APP_STORE_CONNECT_KEY_iD (lowercase i) and preflight fails on APP_STORE_CONNECT_KEY_ID.
This proves a case-sensitive env-var name mismatch.

CONSTRAINTS:
- Use Codemagic documented env vars: APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID.
- Must persist normalized env vars across steps using CM_ENV.
- Keep iOS signing as provisioning profile + certificate references only.
- Provide full-file replacement codemagic.yaml at repo root.

TASKS:
1) Replace root codemagic.yaml with the assistant-provided full YAML.
2) In the preflight step, normalize key id env var:
   - Prefer APP_STORE_CONNECT_KEY_IDENTIFIER, fallback to APP_STORE_CONNECT_KEY_ID, then APP_STORE_CONNECT_KEY_iD.
   - Persist normalized name by writing: echo "APP_STORE_CONNECT_KEY_IDENTIFIER=<value>" >> $CM_ENV
3) Ensure publishing.app_store_connect uses:
   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
4) Commit with message: "Fix ASC env var normalization + stabilize TestFlight publishing"

ACCEPTANCE CRITERIA:
- Preflight succeeds even when only APP_STORE_CONNECT_KEY_iD exists.
- IPA artifact is generated.
- TestFlight upload succeeds.

ROLLBACK:
- Revert commit and retag.
