workflows:
  ios-release-1-0-8:
    name: iOS Release v1.0.8 (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2   # match known-good behavior
    environment:
      groups:
        - appstore_credentials
        - ios_config
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
        EXPECTED_IOS_VERSION: "1.0.8"
        APP_STORE_ID: $APP_STORE_ID
      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          node -v
          npm -v
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Sync iOS (Capacitor)
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install --repo-update

      - name: Install Codemagic CLI tools
        script: |
          set -euo pipefail
          pip3 install codemagic-cli-tools --upgrade

      - name: Set iOS version/build (1.0.8 + unique build)
        script: |
          set -euo pipefail
          chmod +x scripts/ci/ios_set_version_build.sh
          ./scripts/ci/ios_set_version_build.sh

          echo "✅ Info.plist updated:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"

      # THIS is what wires the provisioning profile into the Xcode project (Goodbuild #130 behavior)
      - name: Configure code signing (use profiles)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'
          # Goodbuild shows it generates export options with Apple Distribution + manual signing

      # Force Apple Distribution identity at archive time (prevents “iOS Distribution” mismatch)
      - name: Build archive & IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS' COMPILER_INDEX_STORE_ENABLE=NO DEVELOPMENT_TEAM=$TEAM_ID 'CODE_SIGN_IDENTITY=Apple Distribution' CODE_SIGN_STYLE=Manual"
          # This matches the known-good archive command shape

      - name: Verify IPA version + build (fail-fast)
        script: |
          set -e
          IPA_PATH="build/ios/ipa/App.ipa"
          echo "📦 IPA: $IPA_PATH"
          
          # Extract Info.plist from IPA (it's a zip)
          TEMP_DIR=$(mktemp -d)
          unzip -q "$IPA_PATH" -d "$TEMP_DIR"
          
          # Find Info.plist
          PLIST_PATH=$(find "$TEMP_DIR" -name "Info.plist" -path "*/Payload/*.app/*" | head -1)
          echo "✅ IPA Info.plist: $PLIST_PATH"
          
          # Read version and build
          IPA_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_PATH")
          IPA_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH")
          
          echo "✅ IPA Version: $IPA_VERSION"
          echo "✅ IPA Build:   $IPA_BUILD"
          
          # Cleanup
          rm -rf "$TEMP_DIR"
          
          echo "✅ IPA version/build verified. Safe to publish."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
