workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    # Use the Apple Developer Portal key you configured in Codemagic UI.
    integrations:
      app_store_connect: APEX Business Systems

    environment:
      xcode: 15.4
      groups:
        - appstore_credentials   # APP_STORE_CONNECT_* live here
      vars:
        TEAM_ID: "NWGUYF42KW"
        BUNDLE_ID: "com.apex.tradeline"
        IOS_BUILD_NUM: $PROJECT_BUILD_NUMBER

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install deps & build web
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Ensure iOS platform (idempotent)
        script: |
          set -euo pipefail
          if [ -d ios/App/App.xcodeproj ] || [ -d ios/App/App.xcworkspace ]; then
            echo "✅ iOS project present — skipping 'cap add ios'"
          else
            echo "🆕 Adding iOS platform…"
            npm i -D @capacitor/ios
            npx cap add ios
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          command -v pod >/dev/null 2>&1 || sudo gem install cocoapods --no-document
          pod repo update || true
          pod install --repo-update
          test -d App.xcworkspace || { echo "❌ Missing App.xcworkspace"; exit 1; }

      - name: Fetch signing files (App Store dist)
        script: |
          set -euo pipefail
          app-store-connect fetch-signing-files \
            --issuer-id @env:APP_STORE_CONNECT_ISSUER_ID \
            --key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --type IOS_APP_STORE \
            "$BUNDLE_ID"

      - name: Install certs & apply provisioning profiles
        script: |
          set -euo pipefail
          keychain initialize
          # Add any .p12 downloaded by the fetch step (passwordless or managed by Apple)
          keychain add-certificates --certificate "$HOME/Library/MobileDevice/Certificates/"*.p12 || true
          # Apply profiles to the app project only
          xcode-project use-profiles --project "ios/App/App.xcodeproj"

      - name: Set iOS build number (Info.plist)
        script: |
          set -euo pipefail
          if [ -n "${IOS_BUILD_NUM:-}" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${IOS_BUILD_NUM}" ios/App/App/Info.plist || true
            echo "ℹ️ CFBundleVersion = ${IOS_BUILD_NUM}"
          fi

      - name: Xcode archive (manual signing)
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CURRENT_PROJECT_VERSION="${IOS_BUILD_NUM:-1}" \
            -quiet \
            clean archive

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          # Try to detect a matching profile name from the profiles folder for mapping.
          PROFILE_NAME="$(/bin/ls -1 ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -n1 | xargs -I{} /usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< \"$(security cms -D -i {} )\" || true)"
          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>teamID</key><string>${TEAM_ID}</string>
              <key>stripSwiftSymbols</key><true/>
              <key>compileBitcode</key><false/>
              <key>provisioningProfiles</key>
              <dict>
                <key>${BUNDLE_ID}</key><string>${PROFILE_NAME}</string>
              </dict>
            </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        # Upload & TestFlight actions use the UI integration key
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
