workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: APEX Business Systems  # your Codemagic ASC integration name

    environment:
      xcode: 15.4
      groups:
        - appstore_credentials     # TEAM_ID, BUNDLE_ID, DIST_PROFILE_NAME, ASC vars, etc.
      vars:
        IOS_BUILD_NUM: $PROJECT_BUILD_NUMBER

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install deps & build web
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Ensure iOS platform (idempotent & self-heal)
        script: |
          set -euo pipefail
          PROJ_DIR="ios/App"
          XCPROJ="$PROJ_DIR/App.xcodeproj"
          XCWORK="$PROJ_DIR/App.xcworkspace"

          if [ -d "$XCPROJ" ] || [ -d "$XCWORK" ]; then
            echo "✅ Native iOS project present — skipping add"
          else
            if [ -d ios ]; then
              echo "⚠️  ios/ exists but no Xcode project — recreating cleanly"
              rm -rf ios
            fi
            echo "🆕 Adding iOS platform…"
            npm i -D @capacitor/ios
            npx cap add ios
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          npx cap sync ios

          cd ios/App
          command -v pod >/dev/null 2>&1 || sudo gem install cocoapods --no-document
          pod repo update || true
          pod install --repo-update

          test -d "App.xcworkspace" || { echo "❌ CocoaPods didn't produce App.xcworkspace"; exit 1; }

      - name: Set iOS build number from Codemagic (optional)
        script: |
          set -euo pipefail
          if [ -n "${IOS_BUILD_NUM:-}" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${IOS_BUILD_NUM}" ios/App/App/Info.plist || true
            echo "ℹ️  CFBundleVersion set to ${IOS_BUILD_NUM}"
          else
            echo "↪️  IOS_BUILD_NUM not set; skipping Info.plist patch"
          fi

      - name: Install signing certs & provisioning profiles (uploaded in UI)
        script: |
          set -euo pipefail
          # Pulls the .p12 + .mobileprovision you attached on the app's Code signing page
          keychain initialize
          keychain add-certificates
          echo "🔐 Imported app-level certificates and provisioning profiles."

      - name: Fallback — fetch signing files from App Store Connect
        script: |
          set -euo pipefail
          # If no profiles were pulled from the UI, fetch & install via ASC
          if ! ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision >/dev/null 2>&1; then
            echo "No .mobileprovision found from UI, fetching via App Store Connect…"
            app-store-connect fetch-signing-files \
              --type IOS_APP_STORE \
              --bundle-id "$BUNDLE_ID" \
              --create \
              --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
              --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
              --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
              --output "~/Library/MobileDevice/Provisioning Profiles"
            # Import any downloaded certificates/profiles into the build keychain
            keychain add-certificates
          fi

      - name: Apply provisioning profiles to Xcode project (all targets)
        script: |
          set -euo pipefail
          xcode-project use-profiles --project "ios/App/App.xcodeproj"
          echo "✅ Applied profiles to App and Pods targets"

      - name: Xcode archive (manual signing)
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CURRENT_PROJECT_VERSION="${IOS_BUILD_NUM:-1}" \
            -quiet \
            clean archive

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          : "${DIST_PROFILE_NAME:?Set DIST_PROFILE_NAME to your App Store profile name}"

          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>                 <string>app-store</string>
              <key>teamID</key>                 <string>${TEAM_ID}</string>
              <key>stripSwiftSymbols</key>      <true/>
              <key>compileBitcode</key>         <false/>
              <key>provisioningProfiles</key>
              <dict>
                <key>${BUNDLE_ID}</key>         <string>${DIST_PROFILE_NAME}</string>
              </dict>
            </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
