workflows:
  ios-capacitor-testflight:
    name: 🍏 GOODBUILD iOS TestFlight (Upload-only)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      node: 20.19.6
      groups:
        - ios_config
        - app_store_credentials
      vars:
        # ✅ SINGLE SOURCE OF TRUTH
        APP_VERSION: "1.0.6"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.apex.tradeline"

    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods

    scripts:
      - name: 🔎 Runtime versions (fail fast)
        script: |
          node --version
          npm --version

      - name: 📦 Install dependencies
        script: |
          npm ci --no-audit --prefer-offline

      - name: ✅ GOODBUILD quality + verify gates
        script: |
          npm run lint
          npm run typecheck
          npm run test:unit
          npm run test:e2e:smoke
          npm run verify:app
          npm run verify:icons
          npm run verify:console

      - name: 🧱 Build web assets + sync Capacitor (iOS only)
        script: |
          npm run build
          npx cap sync ios

      - name: 🧩 Assert iOS AppIcon exists (hard fail if missing)
        script: |
          test -f "ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json"
          echo "✅ AppIcon.appiconset present"

      - name: 🍏 Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: 🔢 Set iOS version & build number
        script: |
          cd ios/App
          xcrun agvtool new-marketing-version "$APP_VERSION"
          xcrun agvtool new-version -all "$BUILD_NUMBER"
          cd ../..

      - name: 🔐 Use provisioning profiles (GOODBUILD)
        script: |
          xcode-project use-profiles \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: 📦 Build IPA (GOODBUILD)
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "ios/App/App/ExportOptions.plist" \
            --verbose

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/**/*.xcarchive
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.apex.tradeline

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        # IMPORTANT: Do NOT set beta_groups until the group exists in ASC.
        # This keeps the lane “upload-only” and prevents post-processing failures.
