# ═══════════════════════════════════════════════════════════════════════════════
# TRADELINE 24/7 — iOS Build Pipeline
# GOODBUILD Baseline: Build #77 (Oct 27, 2025) - Commit d075d9b
# ═══════════════════════════════════════════════════════════════════════════════

workflows:
  ios-capacitor-testflight:
    name: iOS • Capacitor -> TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - ios_config
        - appstore_credentials

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

      vars:
        XCODE_SCHEME: App
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        BUNDLE_ID: com.apex.tradeline
        TEAM_ID: NWGUYF42KW
        APP_VERSION: "1.0.1"

      node: 20.11.1
      npm: 10
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Quality gates
        script: npm run lint && npm run typecheck && npm run test:unit

      - name: Playwright smoke
        script: |
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke

      - name: Build archive & IPA
        script: bash scripts/build-ios.sh

      - name: Upload to TestFlight
        script: fastlane ios upload

      - name: Verify artifacts
        script: bash scripts/verify-codemagic.sh

    artifacts:
      - ios/build/export/*.ipa
      - ios/build/TradeLine247.xcarchive
      - playwright-report/**/*
      - dist/**/*
      - build-artifacts-sha256.txt
