workflows:
  ios-capacitor-testflight:
    name: 🍏 GOODBUILD iOS TestFlight (Upload-safe)
    instance_type: mac_mini_m2
    max_build_duration: 60

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "GOODBUILD-*"
          include: true
      cancel_previous_builds: true

    environment:
      groups:
        - ios_config
        - appstore_credentials

      vars:
        APP_VERSION: "1.0.6"
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline

      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default

      # ✅ IMPORTANT: ios_signing MUST live under environment
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    scripts:
      - name: Runtime versions (fail fast)
        script: |
          set -euo pipefail
          node -v
          npm -v
          xcodebuild -version

      - name: Install dependencies
        script: |
          set -euo pipefail
          npm ci --no-audit --prefer-offline

      - name: Ensure iOS marketing icon exists (pre-sync)
        script: |
          set -euo pipefail
          node scripts/ensure-ios-marketing-icon.mjs

      - name: GOODBUILD quality + verify gates
        script: |
          set -euo pipefail
          npm run lint
          npm run typecheck
          npm run test:unit
          npm run test:e2e:smoke
          npm run build
          npm run verify:app
          npm run verify:icons
          npm run verify:console

      - name: Sync Capacitor iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Ensure iOS marketing icon exists (post-sync)
        script: |
          set -euo pipefail
          node scripts/ensure-ios-marketing-icon.mjs

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install --repo-update
          cd ../..

      - name: Set iOS version & build number
        script: |
          set -euo pipefail
          cd ios/App
          xcrun agvtool new-marketing-version "$APP_VERSION"
          xcrun agvtool new-version -all "$BUILD_NUMBER"
          cd ../..

      - name: Use provisioning profiles (GOODBUILD)
        script: |
          set -euo pipefail
          xcode-project use-profiles --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

      - name: Build IPA (GOODBUILD)
        script: |
          set -euo pipefail
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        # ✅ DO NOT set beta_groups until the group definitely exists in ASC.
        # beta_groups:
        #   - Internal Testers
