workflows:
  ios_capacitor_testflight:
    name: "iOS • Capacitor → TestFlight"
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
  groups:
    - appstore_credentials   
      vars:
        APP_VERSION: "1.0.0"           # keep non-empty; do NOT declare APP_BUILD here
      xcode: "16.0"
      cocoapods: "default"
      node: "20.11.1"
      npm: "10"
  scripts:
  - name: Resolve version/build
    script: |
      set -euo pipefail
      : "${APP_VERSION:=1.0.0}"
      APP_BUILD="$(date +%y%m%d%H%M)"
      echo "APP_VERSION=$APP_VERSION" >> "$CM_ENV"
      echo "APP_BUILD=$APP_BUILD"     >> "$CM_ENV"
  scripts:
      - name: "Resolve version/build"
        script: |
          set -euo pipefail
          : "${APP_VERSION:=1.0.0}"
          APP_BUILD="$(date +%y%m%d%H%M)"
          echo "APP_VERSION=$APP_VERSION" >> "$CM_ENV"
          echo "APP_BUILD=$APP_BUILD"     >> "$CM_ENV"
      - name: "Echo ok"
        script: echo "codemagic.yaml parsed. Ready to extend."
 publishing:
   app_store_connect:
    api_key:
      key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      private_key: $APP_STORE_CONNECT_PRIVATE_KEY
      submit_to_testflight: true

