workflows:
  ios_capacitor_testflight:
    name: "iOS • Capacitor → TestFlight"
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        # Create this Codemagic group with masked vars:
        #   APP_STORE_CONNECT_KEY_IDENTIFIER
        #   APP_STORE_CONNECT_ISSUER_ID
        #   APP_STORE_CONNECT_PRIVATE_KEY    (full .p8 contents)
        #   APPLE_TEAM_ID                    (Team ID, e.g., NWGUYF42KW)
        - appstore_credentials
      vars:
        # Safe defaults; override in UI if you want.
        APP_VERSION: "1.0.0"
        # APP_BUILD must be non-empty and parseable as a string/int. We auto-generate if blank.
        APP_BUILD: ""
      xcode: "16.0"
      cocoapods: default
      node: "20.11.1"
      npm: "10"

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Resolve version/build (idempotent)
        script: |
          set -euo pipefail
          : "${APP_VERSION:=1.0.0}"
          if [ -z "${APP_BUILD:-}" ]; then APP_BUILD="$(date +%y%m%d%H)"; fi
          echo "APP_VERSION=$APP_VERSION" | tee -a $CM_ENV
          echo "APP_BUILD=$APP_BUILD" | tee -a $CM_ENV

      - name: Install deps & build web (idempotent)
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Capacitor iOS sync + CocoaPods (idempotent)
        script: |
          set -euo pipefail
          # Ensure iOS folder was created previously (we don't 'cap add ios' on CI)
          npx cap copy ios
          # If you truly need plugin/native updates too, swap copy->sync:
          # npx cap sync ios
          cd ios/App
          pod install

      - name: Set version/build in Info.plist (idempotent)
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" "App/Info.plist" || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $APP_BUILD" "App/Info.plist" || true

      - name: Xcode archive (automatic signing)
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -allowProvisioningUpdates \
            clean archive

      - name: Export IPA (app-store)
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>${APPLE_TEAM_ID}</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/TradeLine247.xcarchive
      - ios/App/Pods/**/*
      - ios/App/App.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        # Optional:
        # beta_groups:
        #   - Internal Testers
