workflows:
  ios-release-1-0-8:
    name: iOS Release v1.0.8 (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # VERIFIED: ONE UNDERSCORE
        - appstore_credentials
        # Importing ios_config as seen in your screenshot
        - ios_config
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
        EXPECTED_IOS_VERSION: "1.0.8"
        APP_STORE_ID: $APP_STORE_ID
      xcode: 16.4
      node: 20.19.0

    scripts:
      - name: Install Dependencies
        script: |
          npm install
          gem install cocoapods

      - name: Set iOS version/build (1.0.8 + unique build)
        script: |
          set -euo pipefail
          chmod +x scripts/ci/ios_set_version_build.sh
          ./scripts/ci/ios_set_version_build.sh

      - name: Build Web Assets & Sync Capacitor
        script: |
          set -e
          npm run build
          npx cap sync ios

      - name: Build IPA (Archive & Export)
        script: |
          set -e
          cd ios/App
          
          pod install
          
          XC_WORKSPACE="App.xcworkspace"
          XC_SCHEME="$XCODE_SCHEME"
          ARCHIVE_PATH="../../build/ios/xcarchive/App.xcarchive"
          IPA_PATH="../../build/ios/ipa"
          EXPORT_PLIST="../../export_options.plist"
          
          # Create Export Options Plist
          cat > "$EXPORT_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>TL247_mobpro_tradeline_01</string>
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>signingStyle</key>
              <string>manual</string>
          </dict>
          </plist>
          EOF
          
          # 1. Archive (CRITICAL FIX: ADDED SIGNING FLAGS)
          xcodebuild archive \
            -workspace "$XC_WORKSPACE" \
            -scheme "$XC_SCHEME" \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            -sdk iphoneos \
            COMPILER_INDEX_STORE_ENABLE=NO \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE="Manual"

          # 2. Export IPA
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST"

      - name: Verify IPA Version (Fail Fast)
        script: |
          set -euo pipefail
          # Load persisted vars (Codemagic exports CM_ENV automatically in later steps)
          chmod +x scripts/ci/verify_ipa.sh
          ./scripts/ci/verify_ipa.sh

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/ios/xcarchive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
