workflows:
  ios-capacitor-testflight:
    name: iOS • Capacitor -> TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 75
    
    environment:
      groups:
        - ios_config
        - appstore_credentials
      vars:
        XCODE_SCHEME: App
        XCODE_WORKSPACE: App/App.xcworkspace
        BUNDLE_ID: com.apex.tradeline
        TEAM_ID: NWGUYF42KW
        APP_VERSION: 1.0.2
      node: 20.11.1
      npm: 10
      xcode: 16.4
      cocoapods: default
    
    # ✅ CRITICAL: This block enables automatic App Store Connect publishing
    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.apex.tradeline
    
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods
    
    scripts:
      - name: Install dependencies
        script: npm ci
      
      - name: Quality gates
        script: npm run lint && npm run typecheck && npm run test:unit
      
      - name: Playwright smoke
        script: |
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke
      
      - name: Build web assets
        script: npm run build
      
      - name: Sync Capacitor for iOS
        script: npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
      
      - name: Set build number
        script: |
          #!/bin/bash
          set -ex
          PLIST="$CM_BUILD_DIR/ios/App/App/Info.plist"
          
          if [ ! -f "$PLIST" ]; then
            echo "Info.plist not found at $PLIST"
            exit 1
          fi
          
          BUILD_NUMBER=${PROJECT_BUILD_NUMBER:-3}
          if [ "$BUILD_NUMBER" -lt 3 ]; then
            BUILD_NUMBER=3
          fi
          
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$PLIST"
          
          echo "Set CFBundleVersion to $BUILD_NUMBER"
      
      - name: Build archive & IPA
        script: bash scripts/build-ios.sh
      
      - name: Verify artifacts
        script: bash scripts/verify-codemagic.sh
    
    artifacts:
      - ios/build/export/*.ipa
      - ios/build/TradeLine247.xcarchive
      - playwright-report/**/*
      - dist/**/*
      - build-artifacts-sha256.txt
    
    # ✅ CRITICAL: Let Codemagic handle publishing automatically via ios_signing
    publishing:
      app_store_connect:
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'

  # ────────────────────────────────────────────────────────────────────────────
  # ANDROID BUILD
  # ────────────────────────────────────────────────────────────────────────────
  android-capacitor-release:
    name: Android • Capacitor bundleRelease
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      groups:
        - android_signing
      node: 20.11.1
      npm: 10
      java: 17
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Quality gates
        script: npm run lint && npm run typecheck && npm run test:unit
      - name: Playwright smoke
        script: |
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke
      - name: Build Android App Bundle
        script: bash scripts/build-android.sh
      - name: Verify artifacts
        script: bash scripts/verify-codemagic.sh
    artifacts:
      - android/app/build/outputs/**/*.aab
      - playwright-report/**/*
      - dist/**/*
      - build-artifacts-sha256.txt

  # ────────────────────────────────────────────────────────────────────────────
  # WEB TESTS
  # ────────────────────────────────────────────────────────────────────────────
  web-tests-only:
    name: Web Tests & Smoke
    instance_type: linux
    max_build_duration: 45
    environment:
      node: 20.11.1
      npm: 10
    cache:
      cache_paths:
        - ~/.npm
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Lint, typecheck, unit tests
        script: npm run lint && npm run typecheck && npm run test:unit
      - name: Build web bundle
        script: npm run build:web
      - name: Install Playwright browsers
        script: npm run test:install-browsers
      - name: Run full Playwright test suite
        script: npx playwright test --reporter=html
    artifacts:
      - playwright-report/**/*
      - dist/**/*
