workflows:
  ios-capacitor-testflight:
    name: iOS • Capacitor -> TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_config
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
        APP_STORE_ID: $APP_STORE_ID
      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    scripts:
      - name: Runtime versions (fail fast)
        script: |
          set -euo pipefail
          node -v
          npm -v
          xcodebuild -version
          node -e "const v=process.versions.node.split('.').map(Number); if(v[0]!==20||v[1]<19){console.error('Node must be >=20.19.0'); process.exit(1)}"

      # Step 1: Install dependencies
      - name: Install dependencies
        script: |
          set -eo pipefail
          npm ci

      # Step 2: Quality gates (lint, typecheck, test:unit)
      - name: Quality gates
        script: |
          set -eo pipefail
          npm run lint
          npm run typecheck
          npm run test:unit

      # Step 3: Playwright smoke (install browsers first)
      - name: Playwright smoke
        script: |
          set -eo pipefail
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke

      # Step 4: Build (includes postbuild verify:app, verify:icons, verify:console)
      - name: Build web assets
        script: |
          set -eo pipefail
          npm run build

      - name: Verify App Store Connect secrets (fail fast)
        script: |
          set -euo pipefail
          missing=()
          [[ -z "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]] && missing+=("APP_STORE_CONNECT_PRIVATE_KEY")
          [[ -z "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ]] && missing+=("APP_STORE_CONNECT_KEY_IDENTIFIER")
          [[ -z "${APP_STORE_CONNECT_ISSUER_ID:-}" ]] && missing+=("APP_STORE_CONNECT_ISSUER_ID")
          if (( ${#missing[@]} > 0 )); then
            echo "Missing required App Store Connect secrets: ${missing[*]}"
            exit 1
          fi

      - name: Install CocoaPods
        script: |
          set -eo pipefail
          npx cap sync ios

      # Step 6: Install CocoaPods
      - name: Install CocoaPods
        script: |
          set -eo pipefail
          cd ios/App && pod install --repo-update

      - name: Set iOS version/build from App Store Connect (1.0.7 + ASC-latest+1)
        script: |
          chmod +x scripts/ci/ios_versioning_asc.sh
          ./scripts/ci/ios_versioning_asc.sh

      # Step 7: Configure code signing (NO manual fetch-signing-files per spec)
      - name: Configure code signing
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      # Step 8: Build archive & IPA
      - name: Build archive & IPA
        script: |
          set -eo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS'"

      - name: Verify IPA version + build (fail-fast preflight)
        script: |
          set -euo pipefail

          # Read expected build number from versioning step
          if [[ ! -f "/tmp/ios_build_number.txt" ]]; then
            echo "❌ Build number file not found - versioning step may have failed"
            exit 1
          fi
          EXPECTED_BUILD=$(cat /tmp/ios_build_number.txt)
          echo "🎯 Expected build number: $EXPECTED_BUILD"

          IPA_FILE=$(ls build/ios/ipa/*.ipa | head -1)
          if [[ -z "$IPA_FILE" ]]; then
            echo "❌ No IPA file found in build/ios/ipa/"
            exit 1
          fi
          echo "📦 Found IPA: $IPA_FILE"

          # Extract Info.plist from IPA
          unzip -q -o "$IPA_FILE" -d /tmp/ipa_extract
          PLIST_PATH="/tmp/ipa_extract/Payload/*.app/Info.plist"
          if [[ ! -f $PLIST_PATH ]]; then
            echo "❌ Could not find Info.plist in IPA"
            exit 1
          fi

          # Read version info
          MARKETING_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_PATH" 2>/dev/null || echo "")
          BUILD_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH" 2>/dev/null || echo "")
          echo "📱 IPA Version: $MARKETING_VERSION"
          echo "🔢 IPA Build: $BUILD_VERSION"

          # Validate against expected values
          if [[ "$MARKETING_VERSION" != "1.0.7" ]]; then
            echo "❌ CRITICAL: Version mismatch! Expected 1.0.7, got $MARKETING_VERSION"
            exit 1
          fi
          if [[ "$BUILD_VERSION" != "$EXPECTED_BUILD" ]]; then
            echo "❌ CRITICAL: Build number mismatch! Expected $EXPECTED_BUILD, got $BUILD_VERSION"
            exit 1
          fi

          echo "✅ IPA version validation passed - ready for TestFlight upload"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID        # beta_groups:
        #   - Internal Testers
