workflows:
  ios-capacitor-testflight:
    name: TradeLine 24/7 iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_config
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
      xcode: 16.4
      node: 20.11.1
      npm: 10
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          set -eo pipefail
          npm ci

      - name: Build web assets
        script: |
          set -eo pipefail
          npm run build

      - name: Sync Capacitor
        script: |
          set -eo pipefail
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -eo pipefail
          cd ios/App && pod install --repo-update

      - name: Set iOS version & build number
        script: |
          set -eo pipefail
          APP_VERSION="${APP_VERSION:-1.0.4}"
          BUILD_NUM=$((RANDOM % 900 + 100))
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/App/App/Info.plist
          echo "Set version to $APP_VERSION ($BUILD_NUM)"

      - name: Fetch and configure code signing
        script: |
          set -eo pipefail
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles \
            --custom-export-options='{"testFlightInternalTestingOnly": true}'
          echo "═══════════════════════════════════════════════════════════"
          echo "✅ CODE SIGNING CONFIGURED"
          echo "═══════════════════════════════════════════════════════════"

      - name: Build archive & IPA
        script: |
          set -eo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS'"
          echo "═══════════════════════════════════════════════════════════"
          echo "✅ iOS ARCHIVE & IPA SUCCESSFULLY BUILT"
          echo "═══════════════════════════════════════════════════════════"
          ls -la build/ios/ipa/

      - name: Upload to App Store Connect (Internal Testing Only)
        script: |
          set -eo pipefail
          echo "[publish] Finding IPA..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          echo "[publish] Uploading $IPA_PATH to App Store Connect..."
          echo "Build marked as 'Internal Testing Only' - no beta review required"
          app-store-connect publish \
            --path "$IPA_PATH" \
            --testflight \
            --beta-group "Internal Testers" || true
          echo "✅ Successfully uploaded to App Store Connect"
          echo "✅ Build is ready for INTERNAL TESTING ONLY"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
