workflows:
  ios_capacitor_testflight:
    name: iOS • Capacitor → TestFlight (Integration + Identities)
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: Created via API   # the key you connected (green dot)

    environment:
      groups:
        - ios_config                      # TEAM_ID, BUNDLE_ID, etc.
      ios_signing:                        # <-- helps Codemagic pick the right cert+profile
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD: "1"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 20.11.1
      npm: 10
      cocoapods: default

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Resolve version/build
        script: |
          APP_BUILD="$(date +%y%m%d%H)"
          echo "Using APP_VERSION=$APP_VERSION / APP_BUILD=$APP_BUILD"

      - name: Install deps
        script: |
          npm ci --no-audit --no-fund

      - name: Build web (ignore lifecycle hooks)
        script: |
          NPM_CONFIG_IGNORE_SCRIPTS=true npm run build

      - name: Verify built assets
        script: |
          node scripts/verify-app.cjs
          node scripts/verify_icons.mjs

      - name: Sync Capacitor + CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod install --repo-update

      - name: Set iOS Info.plist versions
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${APP_VERSION}" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${APP_BUILD}" ios/App/App/Info.plist

      - name: Initialize keychain & add uploaded certs
        script: |
          keychain initialize
          keychain add-certificates     # pulls certs you added in Code signing identities

      - name: Apply provisioning profiles to Xcode project
        script: |
          xcode-project use-profiles    # applies profiles that match ios_signing settings

      - name: Xcode archive (Release)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -allowProvisioningUpdates \
            clean archive

      - name: Export IPA for App Store
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/TradeLine247.xcarchive

    publishing:
      app_store_connect:
        auth: integration                # uses the connected ASC key
        submit_to_testflight: true
