workflows:
  ios_capacitor_testflight:
    name: "iOS • Capacitor → TestFlight"
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups: [appstore_credentials]   # holds the 3 ASC vars (+ optional APPLE_TEAM_ID)
      vars:
        APP_VERSION: "1.0.0"           # keep non-empty; do NOT declare APP_BUILD here
      xcode: "16.0"
      cocoapods: "default"
      node: "20.11.1"
      npm: "10"
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
