workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic_appstore_integration
    environment:
      groups:
        - appstore_credentials
      node: "18.20.0"
      cocoapods: "1.12.1"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD: "1003"
    scripts:
      - name: Install npm dependencies
        script: |
          set -euo pipefail
          npm ci
      - name: Ensure iOS platform and sync
        script: |
          set -euo pipefail
          if [ ! -d ios ]; then
            npx cap add ios
          fi
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install
      - name: Setup signing
        script: |
          set -euo pipefail
          xcode-project use-profiles
      - name: Build .ipa
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-flags="-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
