workflows:
  cross-platform-release:
    name: 🚀 Double Green Release (iOS & Android)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
        - google_play_credentials
        - keystore_credentials
      vars:
        # 📌 SINGLE SOURCE OF TRUTH
        APP_VERSION: "1.0.1" 
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.tradeline247.app"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'release/*'
          include: true
    scripts:
      - name: 📦 Install Dependencies
        script: |
          npm ci --no-audit --prefer-offline
      
      - name: 🧱 Build Web Assets
        script: |
          npm run build
          npx cap sync

      - name: 🍏 Build iOS (Injected Version)
        script: |
          # Inject Version directly into archive command
          cd ios/App
          
          # Set Versioning safely via AGVTool
          xcrun agvtool new-marketing-version "$APP_VERSION"
          xcrun agvtool new-version -all "$BUILD_NUMBER"
          
          cd ../..
          
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/ios/App.xcarchive" \
            -allowProvisioningUpdates \
            MARKETING_VERSION="$APP_VERSION" \
            CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
            clean archive | xcpretty

          xcodebuild -exportArchive \
            -archivePath "build/ios/App.xcarchive" \
            -exportPath "build/ios/export" \
            -exportOptionsPlist "ios/App/App/ExportOptions.plist" \
            -allowProvisioningUpdates

      - name: 🤖 Build Android (Injected Version)
        script: |
          cd android
          # Use standard AGP properties to override version without file editing
          ./gradlew bundleRelease \
            -Pandroid.injected.version.code=$BUILD_NUMBER \
            -Pandroid.injected.version.name=$APP_VERSION \
            -Pandroid.injected.signing.store.file=$(echo $CM_KEYSTORE_PATH) \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - build/ios/export/*.ipa
      - android/app/build/outputs/bundle/release/*.aab
