# codemagic.yaml — TradeLine247 iOS • TestFlight Release
# Uses env group: appstore_credentials
# Vars required in that group:
#   TEAM_ID=NWGUYF42KW
#   BUNDLE_ID=com.apex.tradeline
#   APP_STORE_CONNECT_PRIVATE_KEY=<full .p8 PEM contents>
#   APP_STORE_CONNECT_KEY_IDENTIFIER=<Key ID>
#   APP_STORE_CONNECT_ISSUER_ID=<Issuer UUID>
#   (optional) DIST_PROFILE_NAME=TL247_mobpro_tradeline_01

workflows:
  ios-release:
    name: iOS • TestFlight Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials
      vars:
        IOS_BUNDLE_ID: $BUNDLE_ID
        APP_VERSION: 1.0.0
        APP_BUILD: ""   # auto-filled with timestamp if empty
      xcode: latest
      cocoapods: default
      node: 20.11.1
      npm: 10

    cache:
      cache_paths:
        - ~/.npm
        - ios/Pods

    scripts:
      - name: Resolve build number (idempotent)
        script: |
          set -euo pipefail
          : "${APP_BUILD:=$(date +%y%m%d%H)}"
          echo "▶ Using APP_VERSION=$APP_VERSION APP_BUILD=$APP_BUILD for $IOS_BUNDLE_ID"

      - name: Sanity checks (keys & bundle)
        script: |
          set -euo pipefail
          [ -n "$APP_STORE_CONNECT_KEY_IDENTIFIER" ] || { echo "❌ Missing APP_STORE_CONNECT_KEY_IDENTIFIER"; exit 2; }
          [ -n "$APP_STORE_CONNECT_ISSUER_ID" ] || { echo "❌ Missing APP_STORE_CONNECT_ISSUER_ID"; exit 2; }
          [ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ] || { echo "❌ Missing APP_STORE_CONNECT_PRIVATE_KEY"; exit 2; }
          printf '%s' "$APP_STORE_CONNECT_PRIVATE_KEY" | grep -q "BEGIN PRIVATE KEY" || { echo "❌ APP_STORE_CONNECT_PRIVATE_KEY is not a .p8 PEM"; exit 2; }
          [ -n "$IOS_BUNDLE_ID" ] || { echo "❌ Missing IOS_BUNDLE_ID"; exit 2; }
          echo "✓ Env looks good"

      - name: Install deps & build web (idempotent)
        script: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Capacitor iOS sync + CocoaPods (idempotent)
        script: |
          set -euo pipefail
          npx cap sync ios
          cd ios/App
          pod install --repo-update

      - name: Fetch signing (App Store) and apply profiles
        script: |
          set -euo pipefail
          # Auto-create Distribution cert/profile if missing; strict bundle match
          app-store-connect fetch-signing-files \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            "$IOS_BUNDLE_ID" \
            --create \
            --strict-match-identifier \
            --log-api-calls
          # Apply the downloaded profiles to the Xcode project
          xcode-project use-profiles

      - name: Set version/build in Info.plist (idempotent)
        script: |
          set -euo pipefail
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $APP_BUILD" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/App/App/Info.plist || true

      - name: Xcode archive (Release)
        script: |
          set -euo pipefail
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            clean archive

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>teamID</key><string>$TEAM_ID</string>
              <key>stripSwiftSymbols</key><true/>
              <key>compileBitcode</key><false/>
            </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/TradeLine247.xcarchive
      - ios/App/Pods/**/*
      - ios/App/App.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
