workflows:
  tradeline247-capacitor-testflight:
    name: TradeLine247 → TestFlight (Capacitor)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      node: 20
      cocoapods: default
      groups:
        - appstore_credentials    # contains your ASC env vars
        - ios_config              # contains TEAM_ID, XCODE_*, BUNDLE_ID
      vars:
        TEAM_ID: "NWGUYF42KW"
        BUNDLE_ID: "com.apex.tradeline"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/ios/App/Pods
        - $CM_BUILD_DIR/node_modules

    scripts:
      - name: Verify ASC env presence (names only)
        script: |
          set -e
          echo "=== ENV VAR NAMES PRESENT ==="
          printenv | cut -d= -f1 | grep '^APP_STORE_CONNECT_' | sort || true
          echo "=== REQUIRED CHECKS ==="
          [ -n "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ] || { echo "Missing APP_STORE_CONNECT_PRIVATE_KEY"; exit 1; }
          [ -n "${APP_STORE_CONNECT_ISSUER_ID:-}" ] || { echo "Missing APP_STORE_CONNECT_ISSUER_ID"; exit 1; }
          if [ -z "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ] && [ -z "${APP_STORE_CONNECT_KEY_IDENTIFIE:-}" ]; then
            echo "Missing Key ID var: APP_STORE_CONNECT_KEY_IDENTIFIER"; exit 1;
          fi
          echo "TEAM_ID=$TEAM_ID"
          echo "BUNDLE_ID=$BUNDLE_ID"
          echo "XCODE_WORKSPACE=$XCODE_WORKSPACE"
          echo "XCODE_SCHEME=$XCODE_SCHEME"

      - name: Node install & web build
        script: |
          set -e
          npm ci || npm install
          npm run build || npx ionic build || true

      - name: Sync Capacitor iOS wrapper
        script: |
          set -e
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod repo update
          pod install
          cd -

      - name: Fetch signing using env creds
        script: |
          set -e
          KEY_ID="${APP_STORE_CONNECT_KEY_IDENTIFIER:-$APP_STORE_CONNECT_KEY_IDENTIFIE}"
          app-store-connect fetch-signing-files "$BUNDLE_ID" --create --type IOS_APP_STORE \
            --team-id "$TEAM_ID" \
            --key-id "$KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain initialize
          keychain add-certificates

      - name: Apply provisioning to your workspace
        script: |
          set -e
          xcode-project use-profiles --workspace "$XCODE_WORKSPACE"

      - name: Optional: bump build number from TestFlight
        script: |
          set -e
          # Provide your numeric App Store "Apple ID" as APP_APPLE_ID to enable this.
          if [[ "${APP_APPLE_ID:-}" =~ ^[0-9]+$ ]]; then
            LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_APPLE_ID" || echo 0)
            NEXT=$((LATEST + 1))
            echo "Using next build number: $NEXT"
            agvtool new-version -all "$NEXT" || true
          else
            echo "No APP_APPLE_ID set; skipping auto bump."
          fi

      - name: Non-fatal privacy/encryption lint
        script: |
          set -e
          if ! find . -name "PrivacyInfo.xcprivacy" -print -quit | grep -q . ; then
            echo "WARNING: No PrivacyInfo.xcprivacy found. Ensure privacy manifest if using Required-Reason APIs."
          fi
          INFOPLIST=$(grep -rl --include=Info.plist '<key>CFBundleIdentifier</key>' . | head -n1 || true)
          if [ -n "$INFOPLIST" ] && ! /usr/libexec/PlistBuddy -c "Print :ITSAppUsesNonExemptEncryption" "$INFOPLIST" >/dev/null 2>&1; then
            echo "NOTICE: Consider ITSAppUsesNonExemptEncryption in Info.plist if applicable."
          fi

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-configuration Release \
            --xcargs "DEVELOPMENT_TEAM=$TEAM_ID CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/export_options.plist
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        # Using env-based auth (no integration needed):
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: ${APP_STORE_CONNECT_KEY_IDENTIFIER:-$APP_STORE_CONNECT_KEY_IDENTIFIE}
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal
