workflows:
  ios-capacitor-testflight:
    name: iOS • Capacitor -> TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_config
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
        EXPECTED_IOS_VERSION: "1.0.8"
        APP_STORE_ID: $APP_STORE_ID
      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    scripts:
      - name: Runtime versions (fail fast)
        script: |
          set -euo pipefail
          node -v
          npm -v
          xcodebuild -version
          node -e "const v=process.versions.node.split('.').map(Number); if(v[0]!==20||v[1]<19){console.error('Node must be >=20.19.0'); process.exit(1)}"

      # Step 1: Install dependencies
      - name: Install dependencies
        script: |
          set -eo pipefail
          npm ci

      # Step 2: Quality gates (lint, typecheck, test:unit)
      - name: Quality gates
        script: |
          set -eo pipefail
          npm run lint
          npm run typecheck
          npm run test:unit

      # Step 3: Playwright smoke (install browsers first)
      - name: Playwright smoke
        script: |
          set -eo pipefail
          npx playwright install --with-deps chromium
          npm run test:e2e:smoke

      # Step 4: Build (includes postbuild verify:app, verify:icons, verify:console)
      - name: Build web assets
        script: |
          set -eo pipefail
          npm run build

      - name: Verify App Store Connect secrets (fail fast)
        script: |
          set -euo pipefail
          missing=()
          [[ -z "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]] && missing+=("APP_STORE_CONNECT_PRIVATE_KEY")
          [[ -z "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ]] && missing+=("APP_STORE_CONNECT_KEY_IDENTIFIER")
          [[ -z "${APP_STORE_CONNECT_ISSUER_ID:-}" ]] && missing+=("APP_STORE_CONNECT_ISSUER_ID")
          if (( ${#missing[@]} > 0 )); then
            echo "Missing required App Store Connect secrets: ${missing[*]}"
            exit 1
          fi

      - name: Install CocoaPods
        script: |
          set -eo pipefail
          npx cap sync ios

      # Step 6: Install CocoaPods
      - name: Install CocoaPods
        script: |
          set -eo pipefail
          cd ios/App && pod install --repo-update

      - name: Set iOS version/build (1.0.8 + unique build)
        script: |
          set -euo pipefail
          chmod +x scripts/ci/ios_set_version_build.sh
          bash scripts/ci/ios_set_version_build.sh

      # Step 7: Configure code signing (NO manual fetch-signing-files per spec)
      - name: Configure code signing
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      # Step 8: Build archive & IPA
      - name: Build archive & IPA
        script: |
          set -eo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS'"

      - name: Verify IPA version + build (fail-fast)
        script: |
          set -e
          IPA_PATH="build/ios/ipa/App.ipa"
          echo "📦 IPA: $IPA_PATH"
          
          # Extract Info.plist from IPA (it's a zip)
          TEMP_DIR=$(mktemp -d)
          unzip -q "$IPA_PATH" -d "$TEMP_DIR"
          
          # Find Info.plist
          PLIST_PATH=$(find "$TEMP_DIR" -name "Info.plist" -path "*/Payload/*.app/*" | head -1)
          echo "✅ IPA Info.plist: $PLIST_PATH"
          
          # Read version and build
          IPA_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_PATH")
          IPA_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH")
          
          echo "✅ IPA Version: $IPA_VERSION"
          echo "✅ IPA Build:   $IPA_BUILD"
          
          # Cleanup
          rm -rf "$TEMP_DIR"
          
          echo "✅ IPA version/build verified. Safe to publish."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID        # beta_groups:
        #   - Internal Testers
