workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    # Use ONE auth path only. OPTION A (recommended): env vars
    # If you instead use the Codemagic "Developer Portal" integration, delete the env-var block below
    # and uncomment the `integrations` + publishing.auth=integration block further down.

    environment:
      groups:
        - appstore_credentials   # must contain the three vars below (see notes)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline     # <- your real bundle id
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install deps
        script: |
          npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Apply signing profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          cd ios/App
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        # OPTION A — Env vars (matches docs; do NOT include `auth: integration`)
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY          # the .p8 contents
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER        # Key ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID          # Issuer ID

        submit_to_testflight: true
        beta_groups:
          - Internal Testers

        # OPTION B — Codemagic UI integration (comment out the 3 lines above and use the 2 lines below)
        # auth: integration
        # (and put this at workflow root): integrations: { app_store_connect: <Your-Key-Name> }
