workflows:

  ios-capacitor-testflight:

    name: iOS • Capacitor -> TestFlight

    instance_type: mac_mini_m2

    max_build_duration: 75

    environment:

      groups:

        - ios_config

        - appstore_credentials

      vars:

        XCODE_SCHEME: App

        XCODE_WORKSPACE: App/App.xcworkspace

        BUNDLE_ID: com.apex.tradeline

        TEAM_ID: NWGUYF42KW

        APP_VERSION: 1.0.2

      node: 20.11.1

      npm: 10

      xcode: latest

      cocoapods: default

    cache:

      cache_paths:

        - ~/.npm

        - ~/.cocoapods

        - ios/Pods

    scripts:

      - name: Install dependencies

        script: npm ci



      - name: Quality gates

        script: npm run lint && npm run typecheck && npm run test:unit



      - name: Playwright smoke

        script: |

          npx playwright install --with-deps chromium

          npm run test:e2e:smoke



      - name: Build web assets

        script: npm run build



      - name: Sync Capacitor for iOS

        script: npx cap sync ios



      - name: Install CocoaPods

        script: |

          cd ios/App

          pod install --repo-update



      - name: Set iOS version & build number

        script: |

          set -eo pipefail

          bash ./scripts/set-ios-version-from-codemagic.sh



      - name: Build archive & IPA

        script: bash scripts/build-ios.sh



      - name: 🚀 Upload to TestFlight

        script: |

          set -euo pipefail



          echo "════════════════════════════════════════════════════"

          echo "📤 TESTFLIGHT UPLOAD"

          echo "════════════════════════════════════════════════════"



          # Setup

          KEY_FILE="/tmp/AuthKey.p8"

          MAX_RETRIES=3



          cleanup() { rm -f "$KEY_FILE"; }

          trap cleanup EXIT



          # Validate

          for VAR in APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_PRIVATE_KEY; do

            [ -z "${!VAR}" ] && echo "❌ $VAR not set" && exit 1

          done



          # Create key

          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 --decode > "$KEY_FILE"

          chmod 600 "$KEY_FILE"

          grep -q "BEGIN PRIVATE KEY" "$KEY_FILE" || { echo "❌ Invalid key"; exit 1; }



          # Find IPA

          IPA_PATH=$(cat /Users/builder/clone/ipa_path.txt 2>/dev/null || find /Users/builder/clone/ios/build/export -name "*.ipa" | head -1)

          [ ! -f "$IPA_PATH" ] && echo "❌ No IPA found" && exit 1



          echo "✅ IPA: $IPA_PATH ($(du -h "$IPA_PATH" | cut -f1))"



          # Upload with retry

          for attempt in $(seq 1 $MAX_RETRIES); do

            echo ""

            echo "📤 Attempt $attempt/$MAX_RETRIES..."



            if xcrun altool --upload-app --type ios --file "$IPA_PATH" \

              --apiKey "$APP_STORE_CONNECT_KEY_IDENTIFIER" \

              --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" \

              --verbose; then

              echo ""

              echo "🎉 UPLOAD SUCCESSFUL"

              exit 0

            fi



            [ $attempt -lt $MAX_RETRIES ] && echo "⏳ Retry in 30s..." && sleep 30

          done



          echo "❌ Upload failed"

          exit 1



      - name: Verify artifacts

        script: bash scripts/verify-codemagic.sh



    artifacts:

      - ios/build/export/*.ipa

      - ios/build/TradeLine247.xcarchive

      - playwright-report/**/*

      - dist/**/*

      - build-artifacts-sha256.txt



    triggering:

      events:

        - push

      branch_patterns:

        - pattern: 'main'



  android-capacitor-release:

    name: Android • Capacitor bundleRelease

    instance_type: linux_x2

    max_build_duration: 60

    environment:

      groups:

        - android_signing

      node: 20.11.1

      npm: 10

      java: 17

    cache:

      cache_paths:

        - ~/.npm

        - ~/.gradle

    scripts:

      - name: Install dependencies

        script: npm ci

      - name: Quality gates

        script: npm run lint && npm run typecheck && npm run test:unit

      - name: Playwright smoke

        script: |

          npx playwright install --with-deps chromium

          npm run test:e2e:smoke

      - name: Build Android App Bundle

        script: bash scripts/build-android.sh

      - name: Verify artifacts

        script: bash scripts/verify-codemagic.sh

    artifacts:

      - android/app/build/outputs/**/*.aab

      - playwright-report/**/*

      - dist/**/*

      - build-artifacts-sha256.txt



  web-tests-only:

    name: Web Tests & Smoke

    instance_type: linux

    max_build_duration: 45

    environment:

      node: 20.11.1

      npm: 10

    cache:

      cache_paths:

        - ~/.npm

    scripts:

      - name: Install dependencies

        script: npm ci

      - name: Lint, typecheck, unit tests

        script: npm run lint && npm run typecheck && npm run test:unit

      - name: Build web bundle

        script: npm run build:web

      - name: Install Playwright browsers

        script: npm run test:install-browsers

      - name: Run full Playwright test suite

        script: npx playwright test --reporter=html

    artifacts:

      - playwright-report/**/*

      - dist/**/*