scripts:
  - name: Install deps & build web
    script: |
      set -euo pipefail
      npm ci
      npm run build

  - name: Ensure iOS platform & CocoaPods
    script: |
      set -euo pipefail
      # If the iOS project doesn't exist (fresh runner), create it
      if [ ! -d ios/App/App.xcodeproj ]; then
        echo "iOS platform missing → npx cap add ios"
        rm -rf ios || true
        npx cap add ios
      fi

      # Sync Capacitor + install pods
      npx cap sync ios
      cd ios/App
      pod repo update || true
      pod install --repo-update
      test -d App.xcworkspace || { echo "❌ CocoaPods failed to create workspace"; exit 1; }

  - name: Xcode archive (automatic signing)
    script: |
      set -euo pipefail
      xcodebuild -workspace "ios/App/App.xcworkspace" \
        -scheme "App" \
        -configuration Release \
        -sdk iphoneos \
        -destination "generic/platform=iOS" \
        -archivePath "$CM_BUILD_DIR/App.xcarchive" \
        -allowProvisioningUpdates \
        -quiet \
        clean archive

  - name: Export IPA
    script: |
      set -euo pipefail
      cat > exportOptions.plist <<'PLIST'
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>method</key><string>app-store</string>
        <key>destination</key><string>export</string>
        <key>teamID</key><string>${APP_STORE_CONNECT_TEAM_ID}</string>
        <key>stripSwiftSymbols</key><true/>
        <key>compileBitcode</key><false/>
      </dict>
      </plist>
      PLIST
      xcodebuild -exportArchive \
        -archivePath "$CM_BUILD_DIR/App.xcarchive" \
        -exportOptionsPlist exportOptions.plist \
        -exportPath "$CM_BUILD_DIR/export"
