workflows:
  ios-release-1-0-8:
    name: iOS Release v1.0.8 (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2   # match known-good behavior
    environment:
      groups:
        - appstore_credentials
        - ios_config
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
        TEAM_ID: NWGUYF42KW
        APP_STORE_ID: "6754187965"     # numeric Apple App ID (you set this correctly)
        TARGET_VERSION: "1.0.8"
      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          node -v
          npm -v
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Sync iOS (Capacitor)
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install --repo-update

      - name: Install Codemagic CLI tools
        script: |
          set -euo pipefail
          pip3 install codemagic-cli-tools --upgrade

      # IMPORTANT: this is what your current workflow is missing
      - name: Set iOS version/build (1.0.8 + ASC-latest+1) + persist
        script: |
          set -euo pipefail

          TARGET_VERSION="${TARGET_VERSION:-1.0.8}"

          # Get latest TestFlight build number; if call fails, fallback to a guaranteed-unique integer
          set +e
          LATEST_BUILD="$(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID" 2>/dev/null)"
          STATUS=$?
          set -e

          if [[ $STATUS -ne 0 || ! "$LATEST_BUILD" =~ ^[0-9]+$ ]]; then
            echo "⚠️ ASC lookup failed; using epoch fallback build number"
            NEW_BUILD="$(date +%s)"
          else
            NEW_BUILD="$((LATEST_BUILD + 1))"
          fi

          echo "🚀 Enforcing Version: $TARGET_VERSION"
          echo "🆙 Using Build Number: $NEW_BUILD"

          PLIST="ios/App/App/Info.plist"
          if [[ ! -f "$PLIST" ]]; then
            echo "❌ Missing Info.plist at $PLIST"
            exit 1
          fi

          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $TARGET_VERSION" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $TARGET_VERSION" "$PLIST"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD" "$PLIST"

          echo "APP_VERSION=$TARGET_VERSION" >> "$CM_ENV"
          echo "APP_BUILD_NUMBER=$NEW_BUILD" >> "$CM_ENV"

          echo "✅ Info.plist updated:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"

      # THIS is what wires the provisioning profile into the Xcode project (Goodbuild #130 behavior)
      - name: Configure code signing (use profiles)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'
          # Goodbuild shows it generates export options with Apple Distribution + manual signing

      # Force Apple Distribution identity at archive time (prevents “iOS Distribution” mismatch)
      - name: Build archive & IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS' COMPILER_INDEX_STORE_ENABLE=NO DEVELOPMENT_TEAM=$TEAM_ID 'CODE_SIGN_IDENTITY=Apple Distribution' CODE_SIGN_STYLE=Manual"
          # This matches the known-good archive command shape

      - name: Verify IPA version + build (fail-fast)
        script: |
          set -euo pipefail
          source "$CM_ENV"

          IPA="$(ls -1 build/ios/ipa/*.ipa | head -n 1)"
          echo "📦 IPA: $IPA"

          TMP="$(mktemp -d)"
          unzip -q "$IPA" -d "$TMP"

          PLIST_IN_IPA="$(find "$TMP/Payload" -maxdepth 4 -name Info.plist | head -n 1)"
          if [[ -z "$PLIST_IN_IPA" ]]; then
            echo "❌ Could not find Info.plist in IPA"
            find "$TMP/Payload" -maxdepth 3 -print || true
            exit 1
          fi

          V=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_IN_IPA")
          B=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_IN_IPA")

          echo "✅ IPA Version: $V"
          echo "✅ IPA Build:   $B"

          [[ "$V" == "$APP_VERSION" ]] || (echo "❌ Version mismatch (expected $APP_VERSION)"; exit 1)
          [[ "$B" == "$APP_BUILD_NUMBER" ]] || (echo "❌ Build mismatch (expected $APP_BUILD_NUMBER)"; exit 1)

          rm -rf "$TMP"
          echo "✅ IPA verified. Safe to publish."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
