- name: Ensure iOS platform (idempotent)
  script: |
    set -euo pipefail
    echo "== Capacitor platforms =="
    npx cap ls || true

    # Detect if iOS is already installed (works even if paths differ)
    if npx cap ls | awk '/ios/ && /installed/ { f=1 } END{ exit f?0:1 }'; then
      echo "✅ iOS platform already installed -> skip 'cap add ios'"
    else
      echo "🆕 Adding iOS platform..."
      # Ensure package present (handles repos that didn’t commit /ios)
      npm i -D @capacitor/ios
      npx cap add ios
    fi

- name: Sync iOS & CocoaPods
  script: |
    set -euo pipefail
    # Always sync (copies web + updates native)
    npx cap sync ios

    # Install pods in the native app folder
    cd ios/App
    pod repo update || true
    pod install --repo-update

    # Probes
    test -d App.xcworkspace || { echo "❌ Missing ios/App/App.xcworkspace (pod install failed)"; exit 1; }
    test -d App.xcodeproj || { echo "❌ Missing ios/App/App.xcodeproj (Capacitor add/sync failed)"; exit 1; }
    echo "✅ CocoaPods ready"
