export const paths = {
  home: "/",
  features: "/features",
  pricing: "/pricing",
  faq: "/faq",
  compare: "/compare",
  security: "/security",
  contact: "/contact",
  privacy: "/privacy",
  docs: "/docs",
  previewHealth: "/preview-health",
  login: "/login",
  auth: "/auth",
  dashboard: "/dashboard",
  calls: "/calls",
  callCenterLegacy: "/call-center",
  callLogs: "/call-logs",
  addNumber: "/numbers/new",
  numbersLegacy: "/numbers",
  teamInvite: "/team/invite",
  integrations: "/integrations",
  phoneApps: "/phone-apps",
  forwardingWizard: "/ops/forwarding",
  voiceSettings: "/ops/voice",
  notFound: "*",
} as const;
