// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/utils/env';

const runtimeMode = (import.meta.env?.MODE as string | undefined) ?? process.env.NODE_ENV ?? 'development';
const rawSupabaseUrl = env('VITE_SUPABASE_URL');
const projectId = env('VITE_SUPABASE_PROJECT_ID');
const resolvedSupabaseUrl = (rawSupabaseUrl ?? (projectId ? `https://${projectId}.supabase.co` : undefined))?.replace(/\/+$/, '');
const resolvedAnonKey = env('VITE_SUPABASE_ANON_KEY') ?? env('VITE_SUPABASE_PUBLISHABLE_KEY');

const supabaseConfigured = Boolean(resolvedSupabaseUrl && resolvedAnonKey);
const configurationMessage = 'Supabase environment variables are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY).';

if (!supabaseConfigured && (import.meta.env?.DEV || runtimeMode === 'development')) {
  console.error(`[supabase] ${configurationMessage}`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely detect browser storage to avoid SSR/build ReferenceErrors
const safeStorage: Storage | undefined =
  typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
    ? window.localStorage
    : undefined;

function createDisabledClient(): SupabaseClient<Database> {
  const rejection = () => Promise.reject(new Error(configurationMessage));
  const noop = () => undefined;

  const createDisabledQuery = () => {
    const chain: Record<string, any> = {};
    const chainMethod = () => chain;

    chain.select = chainMethod;
    chain.insert = chainMethod;
    chain.update = chainMethod;
    chain.delete = chainMethod;
    chain.eq = chainMethod;
    chain.match = chainMethod;
    chain.limit = chainMethod;
    chain.order = chainMethod;
    chain.maybeSingle = rejection;
    chain.single = rejection;
    chain.then = (...args: Parameters<Promise<unknown>['then']>) =>
      (rejection() as Promise<unknown>).then(...args);
    chain.catch = (...args: Parameters<Promise<unknown>['catch']>) =>
      (rejection() as Promise<unknown>).catch(...args);
    chain.finally = (...args: Parameters<Promise<unknown>['finally']>) =>
      (rejection() as Promise<unknown>).finally(...args);

    return chain;
  };

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: noop } }, error: new Error(configurationMessage) }),
      getSession: () => Promise.resolve({ data: { session: null }, error: new Error(configurationMessage) }),
      signOut: rejection,
      signInWithPassword: rejection,
      signUp: rejection,
      getUser: () => Promise.resolve({ data: { user: null }, error: new Error(configurationMessage) }),
    },
    functions: {
      invoke: rejection,
    },
    from: () => createDisabledQuery(),
    rpc: rejection,
    channel: () => ({
      subscribe: rejection,
      unsubscribe: noop,
    }),
    removeChannel: noop,
    removeAllSubscriptions: noop,
    getChannels: () => [],
    storage: {
      from: () => ({
        upload: rejection,
        download: rejection,
      }),
    },
  } as unknown as SupabaseClient<Database>;
}

export const supabase = supabaseConfigured
  ? createClient<Database>(resolvedSupabaseUrl!, resolvedAnonKey!, {
      auth: {
        // Only persist session when running in the browser
        storage: safeStorage,
        persistSession: typeof window !== 'undefined',
        autoRefreshToken: true,
      }
    })
  : createDisabledClient();

export const isSupabaseEnabled = supabaseConfigured;
export const supabaseUrl = resolvedSupabaseUrl;
export const supabaseFunctionsBase = resolvedSupabaseUrl
  ? `${resolvedSupabaseUrl}/functions/v1`
  : undefined;