require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

app_ios_dir = File.expand_path(__dir__)
unless Dir.pwd == app_ios_dir
  warn "[Podfile] Switching to iOS app directory: #{app_ios_dir}"
  Dir.chdir(app_ios_dir)
end

platform :ios, '15.0'
use_frameworks! linkage: :static

project_relative_path = 'App.xcodeproj'
project_path = File.join(app_ios_dir, project_relative_path)

unless File.exist?(project_path)
  abort <<~MSG
    Unable to locate #{project_relative_path} at #{project_path}.
    Run 'npx cap sync ios' to generate the Xcode project before installing pods.
  MSG
end

project project_relative_path

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
