require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

app_ios_dir = File.expand_path(__dir__)
Dir.chdir(app_ios_dir) unless Dir.pwd == app_ios_dir

platform :ios, '15.0'
use_frameworks! linkage: :static

project File.join(app_ios_dir, 'App.xcodeproj')
workspace File.join(app_ios_dir, 'App.xcworkspace')

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
