require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

app_dir = File.expand_path(__dir__)
unless Dir.pwd == app_dir
  puts "[pods] Switching to #{app_dir} (was #{Dir.pwd})"
  Dir.chdir(app_dir)
end

project_relative = 'App.xcodeproj'
app_project_path = File.expand_path(project_relative, __dir__)
project_file = File.join(app_project_path, 'project.pbxproj')

unless File.directory?(app_project_path)
  abort "[pods] Expected to find #{project_relative} at #{app_project_path}. Run `npx cap sync ios` first."
end

unless File.exist?(project_file)
  abort "[pods] Missing project.pbxproj inside #{project_relative}. Re-run `npx cap sync ios`."
end

platform :ios, '15.0'
use_frameworks! linkage: :static

project app_project_path

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
