name: Auto-merge Lovable PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto:
    name: enable auto-merge when checks pass
    # Run only for Lovable-authored or Lovable-tagged PRs
    if: >
      github.event.pull_request.user.login == 'lovable[bot]' ||
      contains(github.event.pull_request.title, 'Lovable') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'lovable')
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout so gh doesn't complain about missing .git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Enable auto-merge (squash) for this PR using repo-scoped calls
      - name: Enable auto-merge (squash) if checks pass
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          echo "PR #$PR on $REPO"
          # mark ready (no-op if already ready)
          gh pr ready "$PR" --repo "$REPO" || true
          # arm auto-merge (squash). This just sets the flag; merge happens
          # automatically when all required checks pass.
          gh pr merge "$PR" --auto --squash --repo "$REPO"
          echo "Auto-merge armed for PR #$PR."
