name: Auto-merge Lovable PRs
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
permissions:
  pull-requests: write
  contents: write
jobs:
  auto:
    if: >
      github.event.pull_request.user.login == 'lovable[bot]' ||
      contains(github.event.pull_request.title, 'Lovable') ||
      contains(join(fromJson('["labels"]') != null && github.event.pull_request.labels.*.name, ','), 'lovable')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash) if checks pass
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=${{ github.event.pull_request.number }}
          gh pr ready $PR || true
          gh pr merge --auto --squash $PR
