name: ci/build
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: { contents: read }
jobs:
  gate:
    name: gate
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Compat check for legacy required context 'ci/build'."
          echo "Real builds also run under 'ci/build / web' and 'ci/build / ios/build'."
