name: Cloudflare Purge (Targeted)
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Comma-separated URLs to purge"
        required: true
        default: "https://www.tradeline247ai.com/,https://www.tradeline247ai.com/manifest.webmanifest,https://www.tradeline247ai.com/assets/brand/App_Icons/icon-512.png"
jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    steps:
      - name: Purge
        run: |
          IFS=',' read -ra ARR <<< "${{ github.event.inputs.urls }}"
          JSON=$(printf '%s\n' "${ARR[@]}" | jq -R . | jq -s '{files: .}')
          curl -sX POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
            --data "$JSON" | jq