name: RLS Guard
on:
  pull_request:
    branches: [ main ]
jobs:
  rls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print instructions
        run: |
          echo "Run scripts/sql/report_rls.sql against your CI Supabase DB."
          echo "Fail PR if any rows are returned."